NUTRIENTS = [
    'kcal', 'protein', 'carbs', 'fat', 'fiber', 'sugar', 'salt', 'cholesterol',
    'vitamin_a', 'vitamin_c', 'vitamin_d', 'vitamin_e', 'vitamin_k',
    'vitamin_b1', 'vitamin_b2', 'vitamin_b3', 'vitamin_b6', 'vitamin_b12',
    'folate', 'calcium', 'iron', 'magnesium', 'potassium', 'zinc'
]
NUTRIENT_UNITS = {
    'kcal': 'kcal',
    'protein': 'g',
    'carbs': 'g',
    'fat': 'g',
    'fiber': 'g',
    'sugar': 'g',
    'salt': 'g',
    'cholesterol': 'g',
    'vitamin_a': 'µg',
    'vitamin_c': 'mg',
    'vitamin_d': 'µg',
    'vitamin_e': 'mg',
    'vitamin_k': 'µg',
    'vitamin_b1': 'mg',
    'vitamin_b2': 'mg',
    'vitamin_b3': 'mg',
    'vitamin_b6': 'mg',
    'vitamin_b12': 'µg',
    'folate': 'µg',
    'calcium': 'mg',
    'iron': 'mg',
    'magnesium': 'mg',
    'potassium': 'mg',
    'zinc': 'mg',
}