"""
Django settings for meals_manager project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from celery.schedules import crontab

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-default-for-local')

# SECURITY WARNING: don't run with debug turned on in production!
ENV = os.environ.get('ENVIRONMENT', 'DEV')

DEBUG = ENV != 'PROD'
# DEBUG = True

SESSION_COOKIE_SECURE = False  # must be False for HTTP localhost. Also setting to false for Cloudflare
CSRF_COOKIE_SECURE = False     # must be False for HTTP localhost
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_HTTPONLY = True

if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Trust the X-Forwarded-Proto header from Nginx
if ENV == 'PROD':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

USE_X_FORWARDED_HOST = ENV in ('DOCKER', 'PROD')

# Allow CSRF from your actual host
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:81').split(',')

# Also make sure USE_X_FORWARDED_HOST is set
USE_X_FORWARDED_HOST = True

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')

#SENTRY BUG LOGS
if ENV == "PROD":
    import sentry_sdk
    sentry_sdk.init(
        dsn=os.getenv("SENTRY_DSN"),
        send_default_pii=True,
    )

# Application definition
PROJECT_APPS = [
    'recipes',
    'ingredients',
    'planner',
    'core',
    'users.apps.UsersConfig',
    'api',

]

from datetime import timedelta

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
#     'ROTATE_REFRESH_TOKENS': True,
#     'BLACKLIST_AFTER_ROTATION': True,
# }

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'cloudinary_storage',  # AFTER staticfiles because i only want it to serve media
    'simple_history',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'django_celery_beat',
    'django.contrib.sitemaps',
    'compressor',

    ] + PROJECT_APPS

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

COMPRESS_ENABLED = True          # set True even in DEBUG to test it locally
COMPRESS_OFFLINE = True          # precompress at deploy time (recommended for production)

# Celery
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'


CELERY_BEAT_SCHEDULE = {
    'cleanup-expired-sessions': {
        'task': 'core.tasks.cleanup_expired_sessions',
        'schedule': crontab(hour=2, minute=0),  # nightly at 2am UTC
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/hour',   # anonymous users — by IP
        'user': '300/hour',  # authenticated users
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Nginx on AWS, Whitenoise on Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.Custom405Middleware', # render custom 405 page
    'core.middleware.SignedCookieMiddleware', # extra security
    'core.middleware.IPRateLimitMiddleware', # limit requests per IP
    'core.middleware.SuspiciousActivityMiddleware'  # protect from tampering

]

ROOT_URLCONF = 'meals_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meals_manager.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if ENV == 'PROD':
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
            "OPTIONS": {"sslmode": os.getenv("DB_SSLMODE", "require")}  # for supabase
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("LOCAL_POSTGRES_DB"),
            "USER": os.getenv("LOCAL_POSTGRES_USER"),
            "PASSWORD": os.getenv("LOCAL_POSTGRES_PASSWORD"),
            "HOST": os.getenv("LOCAL_DB_HOST"),
            "PORT": os.getenv("LOCAL_DB_PORT"),
            "OPTIONS": {"sslmode": os.getenv("LOCAL_DB_SSLMODE", "disable")}
        }
    }
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Brevo Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('BREVO_SMTP_HOST')
EMAIL_PORT = int(os.getenv('BREVO_SMTP_PORT', 587))
EMAIL_USE_TLS = os.getenv('BREVO_EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('BREVO_SMTP_USER')
EMAIL_HOST_PASSWORD = os.getenv('BREVO_SMTP_KEY')
DEFAULT_FROM_EMAIL = os.getenv('BREVO_DEFAULT_FROM_EMAIL')
EMAIL_TIMEOUT = 10

JAZZMIN_SETTINGS = {
    "site_title": "Foodganizer Admin",
    "site_header": "Foodganizer",
    "site_brand": "Foodganizer",
    "welcome_sign": "Welcome to Foodganizer Admin",
    "show_sidebar": True,
    "navigation_expanded": True,
    'order_with_respect_to': [
        'auth',
        'users',
        'ingredients',
        'recipes',
        'planner',
        'core',
    ],
}

JAZZMIN_UI_TWEAKS = {
    "theme": "litera", #vapor, solar, lux, pulse, flatly, litera,
}
AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameBackend',
]
CSRF_FAILURE_VIEW = 'users.views.csrf_failure'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'meals_manager': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}



LOGIN_REDIRECT_URL = 'homepage'
LOGOUT_REDIRECT_URL = 'homepage'
LOGIN_URL = 'login'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  #  dev static folder
STATIC_ROOT = BASE_DIR / 'staticfiles'    #  collectstatic

# Compatibility fix for django-cloudinary-storage with Django 4.2+ for AWS
# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

#AWS
# STORAGES = {
#     "default": {
#         "BACKEND": (
#             "cloudinary_storage.storage.MediaCloudinaryStorage" if ENV == 'PROD' # Cloudinary in production
#             else "django.core.files.storage.FileSystemStorage"
#         ),
#     },
#     "staticfiles": {
#         "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
#     },
# }

#Render
STORAGES = {
    "default": {
        "BACKEND": (
            "cloudinary_storage.storage.MediaCloudinaryStorage" if ENV == 'PROD'
            else "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
WHITENOISE_MANIFEST_STRICT = False
